version: '3'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-ES
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - STACK_VERSION=${STACK_VERSION}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - LICENSE=${LICENSE}
      - ES_PORT=${ES_PORT}
      - KIBANA_PORT=${KIBANA_PORT}
      - MEM_LIMIT=${MEM_LIMIT}
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./ca:/usr/share/elasticsearch/config/certs/ca
    networks:
      - esnet
  
  webscrapping:
    build:
      context: .
      dockerfile: dockerfile0102
    volumes:
      - ./output:/app/output

  transformation:
    build:
      context: .
      dockerfile: dockerfile03
    volumes:
      - ./output:/app/output

  import_to_elasticsearch:
    build:
      context: .
      dockerfile: dockerfile04
    command: ["sh", "-c", "sleep 120 && python 04-esconnect.py"]
    volumes:
      - es_certs:/elasticsearch/certs
    depends_on:
      - elasticsearch

volumes:
  es_certs:
    driver: local

  sentiment_anaysis:
    build:
      context: .
      dockerfile: dockerfile05
    volumes:
      - ./output:/app/output

  dashboard:
    build:
      context: .
      dockerfile: dockerfile06
    command: ["sh", "-c", "sleep 120 && python 06-dashboard.py"]
    ports:
      - "8050:8050"
    volumes:
      - ./output:/app/output